### ISSUE TITLE
Support for Vec<EnumType>

### ISSUE THREAD

**Issue by mathstuf** [media-io/yaserde#10]
There's another serde xml library that I filed this issue against here: https://github.com/RReverser/serde-xml-rs/issues/4. I was wondering if this is possible with yaserde. I might get a chance to try it out over the holidays.

**Comment by MarcAntoine-Arnaud** [comment]
Hi Ben,
Yes but SerDe don't cover, and don't want to cover attribute, namespaces etc.
So it's for that I restart a new projet.

Of course it's possible to support `Vec<EnumType>`, it's just a lack of time on my side.
But any contribution are welcome !

It requires to complete related cases like [here](https://github.com/media-io/yaserde/blob/master/yaserde_derive/src/de/expand_struct.rs#L381) for the deserialization.

Just for the quality of the code and the stability, please write unit tests, all are presents [here](https://github.com/media-io/yaserde/tree/master/yaserde/tests).

If you have any question, don't hesitate just ask ;-)

**Comment by mathstuf** [comment]
Thanks for the info. FWIW, this is is for the BulletML file format. An example of a `Vec<Enum>` is [here](https://github.com/mathstuf/rust-bulletml/blob/master/src/data/mod.rs#L52).

**Comment by MarcAntoine-Arnaud** [comment]
So yes the specification is that [one](https://github.com/Noxalus/BulletML/wiki/BulletML-Reference#action) ?
I hope to support something similar to SerDe for enums: https://serde.rs/enum-representations.html
In you case it the externally tagged (the default).
You have to use the rename to match rust Enum with the right naming in the specification.

Interesting use case, as I have already build YaSerde in Wasm, I see your the target ;-)

**Comment by MarcAntoine-Arnaud** [comment]
Hi @mathstuf,
Is it possible to check the new version of the library ?
@DmitrySamoylov as made a very good stuff, and it's now supported !

If it's fine for you, can you close this issue ?
