### ISSUE TITLE
Not sure how to specify the namespace

### ISSUE THREAD

**Issue by bbigras** [media-io/yaserde#15]
Some of my code stopped working with 0.3.7 (it was OK with 0.3.6). I saw that there was a fix/change for namespace stuff.

I'm not sure if I need to specify `#[yaserde(namespace = "...")]`

```rust
#[test]
fn something_de_struct_namespace() {
  #[derive(YaDeserialize, PartialEq, Debug)]
  #[yaserde(
    root = "DocumentProperties"
  )]
  pub struct DocumentProperties {}

  let content = r#"<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">
 <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
</DocumentProperties>
</Workbook>

  "#;
  convert_and_validate!(content, DocumentProperties, DocumentProperties {});
}
```

```
---- something_de_struct_namespace stdout ----
thread 'something_de_struct_namespace' panicked at 'assertion failed: `(left == right)`
  left: `Err("bad namespace for Workbook, found urn:schemas-microsoft-com:office:spreadsheet")`,
 right: `Ok(DocumentProperties)`', yaserde/tests/der_namespace.rs:44:3
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by bbigras** [comment]
> Sorry for the improper version changes ...

Oh no worries. I was able to stay on 0.3.6 before I found the time to open this issue.

I should have given you a better test case. I'm still confused:

```rust

#[test]
fn something_de_struct_namespace() {
  #[derive(YaDeserialize, PartialEq, Debug)]
  #[yaserde(
      prefix = "microsoft_spreadsheet",
      namespace = "microsoft_spreadsheet: urn:schemas-microsoft-com:office:spreadsheet"
  )]
    pub struct Document {
        #[yaserde(rename = "Row")]
        rows: Vec<Row>,
  }

  let content = r#"<?xml version="1.0"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:o="urn:schemas-microsoft-com:office:office"
 xmlns:x="urn:schemas-microsoft-com:office:excel"
 xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
 xmlns:html="http://www.w3.org/TR/REC-html40">

<Worksheet ss:Name="some_name">
<Table ss:ExpandedColumnCount="11" ss:ExpandedRowCount="195" x:FullColumns="1"
   x:FullRows="1" ss:StyleID="s64" ss:DefaultColumnWidth="60.75"
   ss:DefaultRowHeight="15">
<Row ss:AutoFitHeight="0" ss:Height="33" />
</Table>
</Worksheet>

</Workbook>

  "#;
    convert_and_validate!(content, Document, Document {
        rows: vec![Row {
        }]
  });
}
```

```
---- something_de_struct_namespace stdout ----
thread 'something_de_struct_namespace' panicked at 'assertion failed: `(left == right)`
  left: `Err("bad namespace for Row, found urn:schemas-microsoft-com:office:spreadsheet")`,
 right: `Ok(Document { rows: [Row] })`', yaserde/tests/der_namespace.rs:54:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I tried using `namespace = "ss: urn:schemas-microsoft-com:office:spreadsheet"`but I have no idea what I'm doing (about namespaces. I used XMLs often but I have been lucky to not have to care about namespace until now).

> Do you think it will be necessary by default to skip namespace if it's not mentioned ? or safe to wrote it explicitly as Rust spirit...

I'm not sure what this means to be honest.

**Comment by MarcAntoine-Arnaud** [comment]
Okay so,

XML namespace are used to identify the vocabulary used.
And every markup has a namespace.
So in your second example, *Workbook*, * Worksheet*, *Table* uses the default namespace `urn:schemas-microsoft-com:office:spreadsheet`
declaration needs to be done using *xmlns* with an optional rename item after `:` so `xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"` defines an another namespace who requires to prefix items from this dictionnary with the prefix `ss`
So *ss:ExpandedRowCount* and *ss:ExpandedColumnCount* are from the namespace `urn:schemas-microsoft-com:office:spreadsheet`.

To parse your document, I have wrote a small example here who do the job:
https://github.com/media-io/yaserde_examples/blob/master/src/bbigras_namespace.rs
please check it and you can provide any feedbacks on it ;-)

**Comment by bbigras** [comment]
Thank you for the clear explanation and the exemple. My code works now :+1:.

> Do you think it will be necessary by default to skip namespace if it's not mentioned ? or safe to wrote it explicitly as Rust spirit...

I think I might understand this more now. I think it could be useful sometimes to skip them. Like in my case I'm parsing an Excel XML file but only to get some data. I don't care about most of the attributes and I don't want to read all of the specs and implement a specs perfect parser. If new attributes appears with new namespaces I might prefer to ignore them instead of failing.

But it's fine the way it is now.

Merci.
