### ISSUE TITLE
Is there a way to make a struct with alternative namespace?

### ISSUE THREAD

**Issue by RinChanNOWWW** [media-io/yaserde#160]
For example

```rust
#[derive(Debug, YaDeserialize, YaSerialize, Default)]
#[yaserde(namespace = "{namespace}")]
pub struct MyStruct {
   // ...
}
```

I want to the `{namespace}` be alternative.

Or, can I not specify `#[yaserde(namespace = "{namespace}")]` if the XML has a namespace? 

If I don't specify namespace, it will return `Error: bad namespace for xxx, found xxxx`

**Comment by RinChanNOWWW** [comment]
PTAL @MarcAntoine-Arnaud

**Comment by MarcAntoine-Arnaud** [comment]
Hello,
Sorry for the delay.
For namespace, the derive cannot take variable.
Some example are provided in the repo, like  https://github.com/media-io/yaserde/blob/master/examples/src/bbigras_namespace.rs 
2 attributes are important :
- Namespace to declare prefix with the URL, as the xmlns does. You can declare many on a struct. 
- prefix to use the namespace (it can be on the struct or a field), it requires to matches to the prefix defined in attribute namespace.

Is it clear ?

Best regards

**Comment by RinChanNOWWW** [comment]
Thanks for answering. 

What is the best way to deal with the case if the namespace could change? Make two different structs? Is there a simpler way?

**Comment by MarcAntoine-Arnaud** [comment]
Yes it's the simplest.
And using flatten is great to do:
```rust
#[derive(YaDeserialize)]
#[yaserde ...]
struct MyNamespace1 {
  #[yaserde(flatten)]
  fields: Fields
}


#[derive(YaDeserialize)]
#[yaserde ...]
struct MyNamespace2 {
  #[yaserde(flatten)]
  fields: Fields
}

#[derive(YaDeserialize)]
struct Fields {
  ...
}
```

Like that you didn't re-wrote fields.

**Comment by RinChanNOWWW** [comment]
Thanks.
