### ISSUE TITLE
#[yaserde(flatten)] like #[serde(flatten)] ?

### ISSUE THREAD

**Issue by Boscop** [media-io/yaserde#2]
It would be useful to have a way to "inline" struct fields into the parent struct for the purpose of (de)serialization, like this:

```rust
#[derive(YaSerialize, YaDeserialize)]
struct Common {
    a: i32,
}

#[derive(YaSerialize, YaDeserialize)]
struct Foo {
    #[yaserde(flatten)]
    common: Common,
    foo: u8,
}

#[derive(YaSerialize, YaDeserialize)]
struct Bar {
    #[yaserde(flatten)]
    common: Common,
    bar: u64,
}
```

Like [`#[serde(flatten)]`](https://github.com/serde-rs/serde/pull/1179)

**Comment by MarcAntoine-Arnaud** [comment]
Hello @Boscop ,

@DmitrySamoylov has updated the project and supported flatten feature.
Is it ok for you ? if yes, close the issue.

**Comment by Boscop** [comment]
Sorry for the late reply, I get too many notifications..
Yes, it's great, thanks :)
