### ISSUE TITLE
Deserialized fields can't be named `name`

### ISSUE THREAD

**Issue by steven-joruk** [media-io/yaserde#21]
Hi, I've used 1.37 stable and 1.39 nightly. I work around it by using the rename attribute, but the error message is very unclear so maybe this will help others in their search. Sorry if this is a known limitation, but I can't see it documented anywhere.

Here's a minimum example:
```rust
use std::io::Read;
use yaserde::YaDeserialize;
use yaserde_derive::YaDeserialize;
use log::debug;

#[derive(YaDeserialize, Debug)]
struct MyRoot {
    name: String,
}

fn main() {
    let config: MyRoot = yaserde::de::from_str("").unwrap();
    println!("{:#?}", config);
}
```

Error message:
```
error[E0308]: mismatched types
 --> src/main.rs:7:10
  |
6 | #[derive(YaDeserialize)]
  |          ^^^^^^^^^^^^^ expected reference, found struct `std::string::String`
  |
  = note: expected type `&xml::name::OwnedName`
             found type `std::string::String`
```

**Comment by MarcAntoine-Arnaud** [comment]
Hi @steven-joruk ,
Yes currently `name` is used internally as a variable.
But you can use the `rename` feature:

```rust
#[derive(YaDeserialize, Debug)]
struct MyRoot {
    #[yaserde(rename="name")]
    my_variable: String,
}
```

Tell me if it works for you.
Marc-Antoine

**Comment by steven-joruk** [comment]
Yes, this is the work around I was using. It's just a very common identifier and think it would be worth documenting or working around on the library side. Is the limitation from having to use XmlNode::SomeType { **name**, .. }?

**Comment by MarcAntoine-Arnaud** [comment]
Yes I have planed to update variable name. But I have not time for that right now.
If we change the variable name internally, it will remove the limitation ...

**Comment by DmitrySamoylov** [comment]
Looks like it can be closed
