### ISSUE TITLE
Custom serialize issue

### ISSUE THREAD

**Issue by victor-soloviev** [media-io/yaserde#25]
Are there any examples of a custom deserializer and/or serializer definition? This feature is mentioned in README, but I struggle to find out the correct way to use it.

When I try to define a `serialize` function for my type, yaserde serializes it twice during the outer struct serialization for some reason. Here is an example of this issue:

```
#[derive(Default, PartialEq, Debug, YaSerialize)]
struct Date {
	#[yaserde(rename = "Year")]
	year: i32,
	#[yaserde(rename = "Month")]
	month: i32,

	day: Day,
}

#[derive(Default, PartialEq, Debug)]
struct Day {
	value: i32
}

impl YaSerialize for Day {
	fn serialize<W: Write>(&self, writer: &mut yaserde::ser::Serializer<W>) -> Result<(), String> {
		writer.write(XmlEvent::characters("test"));
		Ok(())
	}
}

fn main() {
	let day: Day = Default::default();
	let data: String = to_string(&day).expect("Error serializing Day");
	println!("{}", data);
	println!();

	let date: Date = Default::default();
	let data: String = to_string(&date).expect("Error serializing Date");
	println!("{}", data);
	println!();
}
```
Output:
```
test

<?xml version="1.0" encoding="utf-8"?><Date><Year>0</Year><Month>0</Month>testtest</Date>
```

The example above is synthetic, but it shows the issue. It does not matter if I use begin_element/end_element in my `serialize` function to have tags around value. When called for `Day` it produces "test" once, but when called for 'Date` it serializes the 'day' field twice.

Here is the code produced my macro obtained with `cargo expand`, which indeed has two serializations for `day`:
```
writer.set_start_event_name(Some("day".to_string()));
match self.day.serialize(writer) {
	Ok(()) => {}
	Err(msg) => {
		return Err(msg);
	}
};
writer.set_start_event_name(None);
writer.set_skip_start_end(true);
match self.day.serialize(writer) {
	Ok(()) => {}
	Err(msg) => {
		return Err(msg);
	}
};
let end_event = XmlEvent::end_element();
let _ret = writer.write(end_event);
```

**Comment by MarcAntoine-Arnaud** [comment]
@victor-soloviev can you check the newest version if it's fixed your issue ?

**Comment by MarcAntoine-Arnaud** [comment]
I close the issue, re-open it if needed.
Marc-Antoine
