### ISSUE TITLE
Serializing Option<Vec> causes proc-macro derive panic

### ISSUE THREAD

**Issue by mayankasthana** [media-io/yaserde#5]
```
#[derive(YaSerialize, Debug)]
#[yaserde(root = "root")]
struct StructOptionVec {
  data: Option<Vec<String>>,
}
```
causes

```
error: proc-macro derive panicked
  --> src/main.rs:73:10
   |
73 | #[derive(YaSerialize, Debug)]
   |          ^^^^^^^^^^^
   |
   = help: message: called `Option::unwrap()` on a `None` value
```

**Comment by MarcAntoine-Arnaud** [comment]
Hello,

Thanks for your report, I have reproduced the error. I check to improve the library to add more serialization features.

I come back to you asap,
Marc-Antoine

**Comment by MarcAntoine-Arnaud** [comment]
@mayankasthana is it possible to test updated master branch with a related fix.
If it will be correct, I'll publish a new minor version.

**Comment by mayankasthana** [comment]
@MarcAntoine-Arnaud Thank you for fixing this so quickly. 
I tested with master branch and it works!
