### ISSUE TITLE
Support enum as top level element

### ISSUE THREAD

**Issue by thirtythreeforty** [media-io/yaserde#68]
I have an XML "schema" (extremely ad-hoc, which I did not design) that can be one of two things:
```
<body>
  <usefulData />
</body>
```
or:
```
<Extension version="1.1">
  <binaryData>1</binaryData>
</Extension>
```

I need to be able to deserialize either one of these, and I don't know which one will arrive from the network connection.  So, I wrote an enum:

```
#[derive(PartialEq, Eq, Debug, YaDeserialize)]
pub(super) enum AllTopXmls {
    #[yaserde(rename="body")]
    Body(Body),
    Extension(Extension),
}

// Required for YaDeserialize
impl Default for AllTopXmls {
    fn default() -> Self {
        AllTopXmls::BcXml(Default::default())
    }
}

struct Body { /* ... */ }

#[derive(PartialEq, Eq, Default, Debug, YaDeserialize)]
pub struct Extension {
    #[yaserde(rename="binaryData")]
    pub binary_data: u32,
}
```

Unfortunately, deserializing this does not work:

```
[DEBUG bc::xml] Enum: start to parse "Extension"
[DEBUG bc::xml] Struct: start to parse "Extension"
[DEBUG yaserde::de] Fetched StartElement(Extension, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"}, [version -> 1.1])
[DEBUG yaserde::de] Fetched StartElement(binaryData, {"": "", "xml": "http://www.w3.org/XML/1998/namespace", "xmlns": "http://www.w3.org/2000/xmlns/"})
[DEBUG yaserde::de] Fetched Characters(1)
[DEBUG yaserde::de] Fetched EndElement(binaryData)
[DEBUG yaserde::de] Fetched EndElement(Extension)
thread 'bc::xml::test_binary_deser' panicked at 'called `Result::unwrap()` on an `Err` value: "unknown event EndDocument"', src/bc/xml.rs:258:13
```

Invoking the deserializer on Body or Extension explicitly works fine.  **But I want yaserde to choose.**

Thank you very much for this library.  It is the only serde-like library that knows how to correctly serialize nested structs and it saved my sanity.

**Comment by MarcAntoine-Arnaud** [comment]
Hello @thirtythreeforty,
Thank for the report.

It's first report on that topic, but it can make sense to support that.
It requires to update YaSerDe.

**Comment by MarcAntoine-Arnaud** [comment]
For me it means the Root Enum element requires to be `flatten`. But flatten is not supported for Enum a this point.

**Comment by thirtythreeforty** [comment]
Glad you are following! 

Since I need this, I'd be happy to attempt it if you would give me some pointers about where to implement. (If it's a quick fix and you'd rather do it, that's fine too.) I am only slightly familiar with custom derive, but I have a decent idea of how XML visitors work.

**Comment by MarcAntoine-Arnaud** [comment]
I have started to create an PR to support that.
As you can see the serialization part is done.
I'll continue on the de-serialization side.

**Comment by thirtythreeforty** [comment]
Hey that's awesome, I'll give it a try when deserialization is working.

**Comment by MarcAntoine-Arnaud** [comment]
it's done and merge on master. Can you try ?
If it's fine for you, please close the PR.

**Comment by thirtythreeforty** [comment]
That was fast. Works for me, thank you!

For future Googlers, you need to annotate the top attribute with `#[yaserde(flatten)]`.
