### ISSUE TITLE
(de)serialize ADT (enums)

### ISSUE THREAD

**Issue by vandenoever** [media-io/yaserde#8]
(De)serialization of this type is not implemented yet:
```
struct Test {
    Empty,
    Full(String)
}
```
An XML (de)serialization library could really make a difference in Rust. There are only a few languages that have good [ADT](https://en.wikipedia.org/wiki/Algebraic_data_type) support. But in XML they are common, e.g. [xsd:choice](https://www.w3.org/TR/xmlschema11-1/#element-choice).

**Comment by MarcAntoine-Arnaud** [comment]
Hello,

We are agreed that's not an `Option<Test>` who you target ? (Empty is `None` in Rust and for a value it will be `Some(type)`). If yes, please check [unit tests](https://github.com/media-io/yaserde/blob/master/yaserde/tests/der_option.rs#L41)

For me, in your example, the idea is to have a field `Test` with known value `Empty` but it can take also any `String` value as an extension.

**Comment by vandenoever** [comment]
`Option<T>` is not enough for general `xs:choice` support. These are other examples:
```rust
struct Test {
    Empty,
    One(One),
    Two(TwoA,TwoB),
    Rest(Rest)
}
```

**Comment by MarcAntoine-Arnaud** [comment]
Yes it's exact.
Is it possible to provide a sample of XML related to this model ?

**Comment by vandenoever** [comment]
The last example could have these instances:
`Empty`:
```xml
<test>
  <empty/>
</test>
```
`One`:
```xml
<test>
  <one><oneContent/></one>
</test>
```
`Two`:
```xml
<test>
  <twoA><twoAContent/></twoA>
  <twoB><twoBContent/></twoB>
</test>
```
`Rest`:
```xml
<test>
  <rest><restContent/></rest>
</test>
```

**Comment by MarcAntoine-Arnaud** [comment]
thank you, does it make sense to support a merged ?
```xml
<test>
  <empty/>
  <one><oneContent/></one>
  <twoA><twoAContent/></twoA>
  <twoB><twoBContent/></twoB>
  <rest><restContent/></rest>
</test>
```
Or if this means it's a `Vec<Test>` with *Test* is the `enum`.

**Comment by vandenoever** [comment]
Merged would similar to `struct` instead of `enum`:
```rust
struct Test {
  one: One,
  twoA: TwoA,
  twoB: TwoB,
  rest: Rest
}
```
The point of the choice/enum is that only one state is valid at a time and only the data of that state are available.

**Comment by MarcAntoine-Arnaud** [comment]
Understanded, I'll check to implement it asap. Or any PR can be merged to support that of course ;-)

**Comment by MarcAntoine-Arnaud** [comment]
Hi @vandenoever !
Is it possible to check the new version of the library ?
@DmitrySamoylov as made a very good stuff, and it's now supported !

If it's fine for you, can you close this issue ?
